#:import ElementParagraph components.element_paragraph.element_paragraph.ElementParagraph

<ElementParagraph>:
    text: root.input_text
    readonly: True
    multiline: True
    font_size: 20
    font_family: None
    line_spacing: 7
    font_name: 'fonts/Helvetica'
    background_color: (0, 0, 0, 0)
    cursor_color: (0, 0, 0, 0)
    selection_color: (0, 1, 0, 0.3)
    size_hint_y: None
    height: root.needed_height
    padding: [0, 0, 0, 0]
