#:import ElementImageNoComment components.element_image_no_comment.element_image_no_comment.ElementImageNoComment

<ElementImageNoComment>:
    id: image_div
    size_hint_y: None
    adaptive_height: True
    orientation: 'vertical'
    spacing: '10dp'

    AsyncImage:
        id: image
        source: root.image
        size_hint: (None, None)
        width: image_div.width
        height: self.width / self.image_ratio
